FROM golang:latest

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go buil -v -n -installsufifix cgo -o financialplannergo ./cmd/server

EXPOSE 8080

CMD ["./financialplannergo"]